# Generated by Django 2.0.2 on 2018-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(default='Interests not updated', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shortbio',
            field=models.CharField(default='Bio is not updated', max_length=100),
        ),
    ]
