# Generated by Django 2.0.2 on 2018-09-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180914_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(default='Interests are not updated', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shortbio',
            field=models.CharField(default='Bio is not updated', max_length=100),
        ),
    ]
