# Generated by Django 2.0.2 on 2018-09-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank='True', default=None, upload_to='profile_image'),
        ),
    ]
