# Generated by Django 2.0.2 on 2018-09-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180915_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(default='Interests are not updated.Please add your Interests', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shortbio',
            field=models.TextField(default='Your bio is not updated.Please update it', max_length=200),
        ),
    ]
